version: "3"

tasks:
  test: curl https://127.0.0.1:3001 --tlsv1.3 -v
  test_cert: curl https://127.0.0.1:3001 --tlsv1.3 -v --cacert cert.pem

  run: cargo run

  run_trace:
    cmd: cargo run
    env:
      RUST_LIB_BACKTRACE: 1

  generate_cert:
    cmd: |
      openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 7 -nodes \
        -subj "/C=XX/ST=StateName/L=CityName/O=CompanyName/OU=CompanySectionName/CN=127.0.0.1"
      openssl x509 -outform der -in cert.pem -out cert.cer
